//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiaryService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string BeginDate { get; set; }
        public string EndDate { get; set; }
        public string Description { get; set; }
        public Nullable<long> Type_Id { get; set; }
        public Nullable<long> Frequency_Id { get; set; }
        public Nullable<long> Status_Id { get; set; }
    
        public virtual TaskType TaskType { get; set; }
        public virtual TaskStatus TaskStatus { get; set; }
        public virtual TaskFrequency TaskFrequency { get; set; }
    }
}
